spring.application.name=movie-bot
spring.profiles.active=local

ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3.2

ollama.embedding.url=http://localhost:11434/api/embeddings
ollama.embedding.model=nomic-embed-text

tmdb.api.url=https://api.themoviedb.org/3